const QUERY_KEYS = {
  FETCH_NAVER_LOGIN: 'FETCH_NAVER_LOGIN',
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_ACCOUNT: 'FETCH_ACCOUNT',
  FETCH_CONTACT: 'FETCH_CONTACT',
  VALIDATE_NICKNAME: 'VALIDATE_NICKNAME',
}

export default QUERY_KEYS
