const QUERY_KEYS = {
  FETCH_NAVER_LOGIN: 'FETCH_NAVER_LOGIN',
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_ACCOUNT: 'FETCH_ACCOUNT',
  FETCH_CONTACTS: 'FETCH_CONTACTS',
  FETCH_CONTACT: 'FETCH_CONTACT',
  FETCH_CONTACT_SUMMARY: 'FETCH_CONTACT_SUMMARY',
  VALIDATE_NICKNAME: 'VALIDATE_NICKNAME',
  REDIRECT_ONBOARDING: 'REDIRECT_ONBOARDING',
}

export default QUERY_KEYS
